
# A dockerized badgr-server stack for development
version: '3.3'

services:
  # this container mirrors in the app code and runs the django dev server
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev.api
    depends_on:
      - "db"
      - "memcached"
    command: /badgr_server/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps:/badgr_server/apps
      - ./manage.py:/badgr_server/manage.py
      - ./.docker/etc/settings_local.dev.py:/badgr_server/apps/mainsite/settings_local.py
    networks:
      - badgr
    ports:
      - "8000:8000"
    environment:
      - db_host=db
      - db_name=postgres
      - db_port=5432
      - db_user=postgres
      - db_password=postgres

  # this container runs memcached
  memcached:
    image: 'bitnami/memcached:latest'
    expose:
      - "11211"
    networks:
      - badgr

# this container runs the dockerized postgres db
  db:
    restart: always
    image: mdillon/postgis:latest
    volumes:
        - db:/var/lib/postgresql
    ports:
        - 5432:5432
    networks:
        - badgr

networks:
  badgr:
    driver: bridge
    

volumes:
  badgr_server_dev_db:
  db: